### ISSUE TITLE
Cannot pass additional data with membership config change

### ISSUE THREAD

**Issue by dmolokanov** [railgun-rs/actix-raft#126]
Hello! First of all thanks for maintaining this crate! The code is clean and abstractions are neat!

I know that raft peers discovery is out of the scope of this particular crate but still I want to check if there are known good suggestions for dynamic membership?

I noticed that [riteraft crate](https://github.com/ritelabs/riteraft/blob/main/src/raft.rs#L148) uses additional field in the membership config change request which is used to store address leader and all the rest peers receives the information about the new peer joined. I don't see something similar to propagate a new peer information to all nodes in cluster so far. 

Another idea is to make it as a `ClientWriteRequest`, but since all ClientRequest processed by a storage I doubt it is a good place to handle this update: address is used in the `RaftNetwork` implementation and it'll mean `RaftStorage` is tightly coupled with `RaftNetwork` which is bad in general.

Any thoughts/suggestions?

**Comment by thedodd** [comment]
Hey there 👋 

> I want to check if there are known good suggestions for dynamic membership?

So, the dynamic membership system is fully functional and tested. Are you asking what is the best way to have peer discovery actualize membership changes?

Ultimately, every config change is propagated to all members of the cluster by the leader. These are propagated as standard Raft entries. The [`change_membership`](https://docs.rs/async-raft/0.6.1/async_raft/raft/struct.Raft.html#method.change_membership) method on the Raft handle is what triggers such changes. I would highly recommend that you review the [Dynamic Membership](https://async-raft.github.io/async-raft/dynamic-membership.html) chapter of the guide (it is quite short). 

Hopefully that is helpful info. Keep me posted.

**Comment by dmolokanov** [comment]
Yes, my questions is about 2 things: peer discovery and cluster membership changes. Right now `change_membership` has following signature: 
```rust
pub async fn change_membership(&self, members: HashSet<NodeId>) -> Result<(), ChangeConfigError>
``` 
As you can see there is only `NodeId` in the method and there is no place to add an address of newly connected node. I think this address can be added on application level via RPC method call like `join_cluster` and the current leader will receive the address of the node. Is it possible to propagate this address to all nodes in the cluster via raft?

The use case I'm thinking about:
1. 3-nodes cluster is running
2. 4th node make RPC `join_cluster` request to the current leader
3. In the handler leader calls `raft.add_non_voter(4)` and `raft.change_membership([4])
4. After change membership request is propagated to all nodes in the cluster every peer knows about the new NodeId=4, but they only leader knows how to connect to this new node

**Comment by thedodd** [comment]
Ah, I see where the difficulty is. In `4.` specifically, all nodes should be running peer discovery. As node IDs propagate as part of the config system, every node should be equipped with what it needs to establish a connection to a node by ID. Typically applications will maintain a mapping of node IDs to their active connections or address info to make a connection. Only the leader can make config changes, but the Raft object exposes multiple mechanisms to check which node is the leader. I would recommend using the metrics system to observe leadership changes, and your app can modify its behavior as needed.

On that last note, I would recommend against building and tearing down node to node connections. Node to node connections should last for as long as possible after a proper handshake protocol and such, as TCP setup can be expensive if done too often. With heartbeats and active data producers, that will be a lot.

**Comment by dmolokanov** [comment]
> Typically applications will maintain a mapping of node IDs to their active connections or address info to make a connection.

Got it. Independent registry required on each raft node: mdns or separate service discovery service. 

> On that last note, I would recommend against building and tearing down node to node connections.

Other words ideally it should be long lived connections

Thanks for clarification!

**Comment by thedodd** [comment]
@dmolokanov let me know if there is anything else I can help out with. I'll close the issue for now, but definitely let me know if there is anything else here that we need to address, and I'm happy to re-open.
