### ISSUE TITLE
`forward_client_write_request()` appears to only error?

### ISSUE THREAD

**Issue by avantgardnerio** [railgun-rs/actix-raft#142]
I'm getting the error: 

```
IoError("Status { code: Internal, message: \"the client write request must be forwarded to the cluster leader\"
```

And it's probably because I'm doing something wrong, but I'm very confused by the implementation of `forward_client_write_request()`, as it appears to either create an error, or be unreachable, but does not seem to forward client write requests:

```
    /// Forward the given client write request to the leader.
    #[tracing::instrument(level = "trace", skip(self, req, tx))]
    fn forward_client_write_request(&self, req: ClientWriteRequest<D>, tx: ClientWriteResponseTx<D, R>) {
        match req.entry {
            EntryPayload::Normal(entry) => {
                let _ = tx.send(Err(ClientWriteError::ForwardToLeader(entry.data, self.current_leader)));
            }
            _ => {
                // This is unreachable, and well controlled by the type system, but let's log an
                // error for good measure.
                tracing::error!("unreachable branch hit within async-raft, attempting to forward a Raft internal entry");
            }
        }
    }
```

Is it possible to explain why this function doesn't seem to do what the name implies?

**Comment by drmingdrmer** [comment]
You are right, `forward_client_write_request()` does nothing but just informs the caller to forward the request to the leader.

The forwarding must be done by the caller after checking for the `ForwardToLeader` error.

**Comment by avantgardnerio** [comment]
Thanks, that makes sense.
