### ISSUE TITLE
`snapshot_dir` in `Config`?

### ISSUE THREAD

**Issue by justinlatimer** [railgun-rs/actix-raft#36]
It looks like the `snapshot_dir` field of `Config` might actually be a detail of the `Storage` implementation - I couldn't find another place it's used in the Raft implementation, it's just passed by the user when constructing their storage. Could this be left up to the storage implementer?

**Comment by thedodd** [comment]
Let me take a look through the code again. I'm tempted to say that it is needed somewhere in the storage interface (above the actual storage impl), but perhaps it is no longer used and was factored out as things evolved. I'll check back in shortly.

**Comment by thedodd** [comment]
@justinlatimer btw, I'm finishing up my work over in #59, and it resolves this issue. You were correct that it is unneeded for the core Raft components of this crate.
