### ISSUE TITLE
Time based state changes

### ISSUE THREAD

**Issue by Diggsey** [railgun-rs/actix-raft#44]
How might one change the replicated state as a result of timed events?

For example, let's say I want to partition data among some client applications. This might work by having each client send a heartbeat request to the raft cluster every few seconds. If a client fails to send a heartbeat within a certain time, I want to reassign its partitions to other clients and update the replicated state to reflect this change.

However, I don't want every node to be looking for "timed out" clients because they'd probably conflict. I don't want nodes to "own" the clients they talk to because then if the node goes down it won't be able to revoke the partitions from the clients it was connected to.

My guess would be that I should send "timeout" changes from the leader, but the only way to know if the node is the leader seems to be via the metrics trait. Is that how you would recommend achieving this?

On a related note: the system currently follows a strict request/response model for clients. What if I want to push information to a client in response to a state change?

**Comment by thedodd** [comment]
Hey @Diggsey. Some projects will use a dedicated "type" of node in their cluster (which is outside of the Raft spec) to do things like shard coordination, placement and the like. It sounds like your use case a somewhat close to this type of things as well. 

I would recommend building something on top of the abstractions you have access to from this crate. For example, perhaps you could have a task which will execute the logic you mentioned above, but it will only live on the leader node. You should observe cluster state / leadership changes through the metrics system (that is a big part of what it is for).

> push information to a client in response to a state change?

A project that I've been building using this crate does exactly that. There is a lot of flexibility on this front. There are a few things you will need:
- some open connection to the client (maybe a WebSocket or some other long-lived TCP connection).
- as events transpire in your actix-raft cluster, your app can look up the clients which need to receive the data based on your own logic and such. Then you should be able to just send the data payload to the client over the open connection.
- you will need your own wire protocol for this. Building on top of TCP is pretty logical. Fortunately, this crate (actix-raft) is completely transport agnostic, so if you wanted to, you could even use WebSockets (TCP/HTTP) with a wire protocol defined using protobuf (I've had good success with that historically).

Let me know what you think. Hopefully this response helps `:)`

**Comment by Diggsey** [comment]
Thanks, I'm slowly progressing on this. I should have clarified in my first message that these "clients" are not part of the raft cluster - the idea is to use a (small) raft cluster to provide a consistent partitioning of data for those (stateless) clients when they are looking for work to do.

One thing that's odd to me is the required directory path for storing log snapshots - I was intending to keep everything in-memory as the state I'm storing is only meaningful when there are clients connected. If the cluster shuts down the partition data can just be thrown away.

**Comment by thedodd** [comment]
@Diggsey nice. Sounds like a solid use case.

> One thing that's odd to me [...] directory path for storing log snapshots

So, in order to be fully compliant with the Raft spec, snapshotting is needed. If you don't need snapshots, you can just disable snapshotting when you initialize Raft: https://docs.rs/actix-raft/0.4.3/actix_raft/config/enum.SnapshotPolicy.html#variant.Disabled If snapshots are disabled, you can just provide a path to a `/tmp` or the like. It won't be used.

Also, the test code in this repo uses an in-memory store as well. So if you want an example of building a storage layer using a similar pattern, feel free to give it an eye `:)`.

**Comment by thedodd** [comment]
@Diggsey mind closing this ticket if you don't have any additional items to be addressed here?

**Comment by Diggsey** [comment]
Sure
