### ISSUE TITLE
InitialState does not implement Default

### ISSUE THREAD

**Issue by Diggsey** [railgun-rs/actix-raft#46]
The [documentation for `GetInitialState`](https://docs.rs/actix-raft/0.4.3/actix_raft/storage/struct.GetInitialState.html) says:

> If no such entry exists due to being the first time the node has come online, then the default value for InitialState should be used.

However, `InitialState` does not implement `Default`, and neither does `HardState`.

**Comment by thedodd** [comment]
@Diggsey btw, the docs that I had there were definitely misleading 😬😬😬 sorry about that. And sorry that it has token so long to get this stuff updated.

I'm finishing up my work over in #59 and have updated the docs for the `InitialState` type to resolve this confusion.

**Comment by Diggsey** [comment]
Nice :)
