### ISSUE TITLE
Decouple snapshots from the filesystem

### ISSUE THREAD

**Issue by Diggsey** [railgun-rs/actix-raft#49]
As we discussed previously, I'm using an in-memory store as I don't need persistence, but I would like to be able to use the snapshot/log-compaction feature to avoid the memory usage growing indefinitely and to make it easier for new nodes to catch up with the leader.

Unfortunately, the current snapshot feature seems intricately coupled with the filesystem, in that actix-raft directly streams results from a file on disk. While I think it would be nice to keep this as a "drop-in" snapshot implementation, I think this should be an implementation detail of the Storage type. Furthermore, I think it's a little odd how some of the APIs operate at a "chunk" level, whereas some operate via file names.

What I would like to see is for `CreateSnapshot` and `InstallSnapshot` to each be split into two parts. such that the second part could be shared between them, so we'd have something like:

- `CreateSnapshot`
  This would take a log range and would save a corresponding snapshot *somewhere* (filesystem, memory, wherever). It would return an opaque snapshot ID.

- `SupplySnapshot`
  This would take no arguments. It would return a new opaque snapshot ID and something implementing `AsyncWrite`. Instead of the current "chunk"-based API, this crate should simply write the snapshot data into the `AsyncWrite` object, calling `flush` where necessary so that there's no need for the per-chunk callback.

- `InstallSnapshot`
  This would take a log range and an opaque snapshot ID produced by a call to `CreateSnapshot` or `SupplySnapshot` from the same node and would implement the logic to compact the log. To aid this, the "path" in EntrySnapshotPointer would be replaced with the opaque snapshot ID. The storage implementation could also use this point to delete other snapshots (as actix-raft should guarantee not call either of the other two methods whilst `InstallSnapshot` is in progress).

Finally, the directory path from the initial config would be dropped, as it will no longer be necessary.

**Comment by thedodd** [comment]
I can definitely see value in decoupling the snapshot system from the filesystem and instead using the Async Read & Write interfaces. That will definitely make it more flexible, though I'll have to review the code their again and ensure that we can still have a robust interface. 

I'll need a little time to re-engage on this front, so do not feel hindered by me. Feel free to make the changes which you see fit, and we can iterate as needed. A few things to keep in mind:
- if we are going to abstract over the storage medium for snapshots, then perhaps we need to create a new set of traits for this, similar to the network & storage traits. If we do this, perhaps we can ship two default FS & in-mem snapshot engines. That would be cool.
- let's make sure that whatever approach we take, we've reviewed its behavior against the Raft spec.
- it is my suspicion that a lot of this code (not just snapshots) will be able to be improved & simplified once we update to the latest version of actix & tokio, as we will be able to use async/await for many of the handlers & methods internally. We can update a lot of the code to use async_traits and the like as well if needed. So, we could knock that out first (depending on your timeline), or we can refactor this bit first.

**Comment by Diggsey** [comment]
> if we are going to abstract over the storage medium for snapshots, then perhaps we need to create a new set of traits for this, similar to the network & storage traits

Maybe - I don't know if it makes sense to split snapshots from storage though as they are quite closely linked.

I do like the idea of supplying some default implementations for these traits as this has been one of the hardest parts for me in using the crate - the sheer amount of stuff that needs to be implemented! It would be cool if I could plug in (at least temporarily) some reference implementations.

> it is my suspicion that a lot of this code (not just snapshots) will be able to be improved & simplified once we update to the latest version of actix & tokio,

Yes! This was the other biggest pain point for me. The async ecosystem has improved immeasurably since this version of actix, and it really shows when trying to go back to the older way of doing things. Is there anything I can do to help out with that transition?

**Comment by thedodd** [comment]
> Is there anything I can do to help out with that transition?
Unfortunately I don't think so. I just need to find the time to re-engage here. I've been in the middle of launching two different products for a while now. 

One thing that is good to report is that I am not actually blocked on Actix core itself supporting async await on the Actor::handle methods. We can keep them mostly the same after the upgrade, and then just update all of the other internal methods and interfaces to be async. That will be a HUGE win. So hopefully I'll be able to get started on this soon. I'll try to start the process this weekend.

**Comment by raultang** [comment]
I came across similar things here: to snapshot rocksdb as rocksdb have its only snapshot mechanism:
`let snapshot = db.snapshot();`
what I need to do is iterating the snapshot and send to follower node.
> I can definitely see value in decoupling the snapshot system from the filesystem and instead using the Async Read & Write interfaces.

I too would like to have this interface separated which I can ship my own snapshot.
On this interface also can build some default file/memory implementations.

**Comment by thedodd** [comment]
@Diggsey && @raultang hey folks! Just wanted to give you an update that I am finishing up my work over in #59, and the snapshot interface is GREATLY improved IMHO. Everything is based on the `AsyncRead`, `AsyncWrite` & `AsyncSeek` traits. The storage engine interface for this stuff is much more simple now as well. I'm quite happy with it.

I'm hoping to cut an alpha release of this code soon (this week I hope)! I would definitely appreciate any feedback you all might have on the new interface. It should be stable at this point, though I still have some docs, tests and other similar tasks to finish up in that PR.

**Comment by raultang** [comment]
Great news, @thedodd the tokio version is exciting:) And the new trait looks much generic, with the `AsyncWrite` and `AsyncRead` interface definitely easy to implement my own snapshot.
