### ISSUE TITLE
Inconsistency with Raft spec

### ISSUE THREAD

**Issue by Diggsey** [railgun-rs/actix-raft#51]
From the spec:
> To prevent this problem, servers disregard RequestVote RPCs when they believe a current leader exists. Specifically, if a server receives a RequestVote RPC within the minimum election timeout of hearing from a current leader, it does not update its term or grant its vote.

The code does not appear to implement this behaviour.

On the other hand, implementing this behaviour seems like it could cause problems: if one node in a cluster temporarily loses connectivity then its "term" may increase beyond the rest of the cluster. When connectivity returns, this node will never be able to rejoin the cluster: it will always refuse AppendEntriesRequests from the leader due to its own "term" being ahead, but it will always fail to win VoteRequests because other nodes will still be receiving heartbeats from the leader.

I can only assume that servers are expected to update themselves with the "term" in a VoteRequest, even if that VoteRequest is going to be ignored due to this reason. However, this would seem to defeat the point of this change, which is intended to prevent ex-members from disrupting the cluster unnecessarily.

**Comment by Diggsey** [comment]
Hm, looks like there are some known problems around this. The accepted solution seems to be to implement some form of PreVote request instead of the change I quoted above:

https://openlife.cc/system/files/4-modifications-for-Raft-consensus.pdf

**Comment by thedodd** [comment]
Yea, I remember squaring with this problem in the Raft spec a year or so ago. I implemented an alternative pattern. Need to find it in the code.

**Comment by ryanjackgit** [comment]
the same problem, if one node in a cluster temporarily loses connectivity then its "term" may increase beyond the rest of the cluster. then  this node will become Candidate always, Need PreVote.

**Comment by thedodd** [comment]
Yea, reviewing the paper here (https://www.openlife.cc/sites/default/files/4-modifications-for-Raft-consensus.pdf) I do think that implementing a pre-vote mechanism should be fine. 

As an aside ... I've been pretty concerned recently about the future of the Actix project. It is definitely going through some hard times these days.

I've been strong considering moving off of Actix, and just directly onto Tokio for the next release. Do you guys have any thoughts on that? @ryanjackgit @Diggsey 

Also, I'm still pretty time constrained, but I've been working through the design of the new pure-tokio version, and I'm pretty stoked about it. Any and all feedback is welcome.

**Comment by Diggsey** [comment]
I also have had some concerns about actix. However, I still feel that "vanilla" tokio is still quite painful to use, and the actor model is very nice for modelling this sort of problem.

I'm currently pursuing my own concept for an actor system. I had an idea for a way to integrate more cleanly with the trait system and async/await that would remove a lot of the annoying boilerplate from actix. However, this is still extremely early and I've been struggling with compiler limitations: what I want to do is still possible it just requires a few more allocations than I would like 😦 Still, it's likely that I'll be able to remove these as compiler support improves, and anyway performance is not my primary goal.

**Comment by thedodd** [comment]
Yea, the core of the idea I've been working towards is still very actor model like, but it is specific to this repo's needs (so it won't be tied to anything other than tokio), and it is based around a few simple concepts:
- an "actor" would just be a spawned task (one of our currents actors, like a replication stream).
- it will be encapsulated in a specialized "addr" type which holds MPSC senders for all of the different message types which the actor can receive.
- the actor's internal loop will just be a `select!` invocation which will consume all of the different MPSC streams, and do whatever work it needs to do. 

Also, per some feedback from folks, I'm thinking I will change the Storage & Network traits over to be just standard traits (using `async-trait` for async/await support), and then internally the Raft crate will just pipeline requests going out to these types for linearizability and such.

@Diggsey thoughts?

Also, definitely keep me posted on your actor project. I would be happy to review and provide feedback when ready.

**Comment by Diggsey** [comment]
That sounds reasonable: it's actually very much in line with how my actor system will work.

This is the design I'm trialling:
1) Each actor is actually a special futures-aware RwLock. The RwLock uses a kind of inversion of control, where the RwLock itself is spawned as a task, and when you want to read/write to the contents, you do that by sending a closure via a channel to the RwLock which it will then execute.

    The advantages are: no unsafe code necessary, maximum throughput (the RwLock just runs these closures one after the other as fast as it can with no overhead in between, all the overhead sits outside the critical section)

2) You never define any message types. You simply define a trait with some methods, eg:

    ```rust
    #[actor]
    trait MyActorInterface {
        fn do_one_thing(&self, arg: i32);
        fn do_another_thing(&self);
    }
    ```

    Internally the `#[actor]` attribute does generate a message enum with variants for each possible method call, but you never interact directly with that message type.

3) You don't need tons of boilerplate to implement the actor:

    ```rust
    #[actor]
    impl MyActorInterface for MyActorStruct {
        async fn do_one_thing(&mut self, arg: i32) {
            self.state +=arg;
            ...
        }
        async fn do_another_thing(&self) {
            ...
        }
    }
    ```

   Things of interest:
    - In the *implementation* you can use `&mut self` - the trait will always use `&self` types. This works because the method implementation is wrapped and sent to run in the RwLock, where you can freely update your state without worrying about concurrency issues.
    - If you use `&self` in the implementation, it will be sent to the RwLock as a "read" operation, so multiple async methods using `&self` could be running at the same time in the RwLock/actor.
    - Methods can optionally be `async`. Again this doesn't affect the trait signature, it just affects what is sent to the RwLock. If a `&mut` method is async, no other methods can run until it finishes.

4) "Results" work by passing in a oneshot channel as a final argument:


    ```rust
    #[actor]
    trait MyActorInterface {
        fn get_a_response(&self, res: Sender<i32>);
    }
    ```

    However, the `#[actor]` attribute will automatically add a default implemented method:

    ```rust
        fn call_get_a_response(&self) -> Receiver<i32> {
            let (tx, rx) = oneshot::channel();
            self.get_a_response(tx);
            rx
        }
    ```

    Which effectively means you can `await` trait methods directly, but also means that you can forward results across multiple calls with zero overhead by reusing the same oneshot channel if you really want to.

**Comment by ryanjackgit** [comment]
I think it's pretty good if it is directly base on tokio, I don't even know actix actor before i use actix-raft.but I'm very familiar with tokio. In order to use actix-raft I had to first learn to use actix.Sometimes I even wonder why use actix. actix-raft library api is easy to undstand and clean. as long as keep this,I think moving off of Actix is not a problem.on the other hand,Async IO is an important part of Rust .and most people should be familiar with it more and less. @Diggsey thoughts is very good too.

**Comment by Diggsey** [comment]
I got the basics of my actor system working - the procedural macros were hard work!

https://github.com/Diggsey/act-zero

**Comment by thedodd** [comment]
@Diggsey @ryanjackgit just wanted to give you all a heads-up that I've addressed this issued directly as part of the updates in #59. Hoping to get that PR landed soon.
