### ISSUE TITLE
Actor system eventually fails

### ISSUE THREAD

**Issue by joshgev** [railgun-rs/actix-raft#57]
Hi!

I've been testing my Raft application and I saw some strange related my `VoteRequest` handler and the `SaveHardState` handler.  I started stripping the code down to see where the issue was and, to further simplify things, I even started testing with just one node (though Raft expects 2, so the single node does attempt to become leader).  For the purposes of this post, I will show my very simplified `VoteRequest` handler:

```
impl Handler<messages::VoteRequest> for AppNetwork {
    type Result = ResponseActFuture<Self, messages::VoteResponse, ()>;

    fn handle(&mut self, msg: messages::VoteRequest, _ctx: &mut Self::Context) -> Self::Result {
        let f = wrap_future(
            async move {
                println!("VoteRequest target: {}", msg.target);
                time::delay_for(std::time::Duration::from_millis(50)).await;
                println!("Done sleeping");
                Err(())
            }
            .boxed_local()
            .compat()
        );

        Box::new(f)
    }
}
```

Tada!  It doesn't do anything: it just fails after a bit.  Since the node thinks there is another node it should talk to, this code does get triggered.  Initially, everything is fine: the node keeps trying at the vote as it should and the output looks like this:

```
VoteRequest target: 1
Done sleeping
VoteRequest target: 1
Done sleeping
VoteRequest target: 1
Done sleeping
VoteRequest target: 1
Done sleeping
...
```

My understanding is that this should basically go on forever since I never bring up the second node.  But, eventually, the handler starts getting hung up on the sleep statement, so that the output looks like this:

```
VoteRequest target: 1
VoteRequest target: 1
VoteRequest target: 1
VoteRequest target: 1
VoteRequest target: 1
VoteRequest target: 1
VoteRequest target: 1
...
```
When we get here, the system never seems to recover.

At some point in my debugging, I thought it might be possible that _another_ vote was getting started even though a future already existed for a previous vote requests, causing the extant future to get dropped and never completed.  This doesn't explain why the system doesn't recover, but on a whim I changed the min/max vote request timeouts. Initially I tried (2000, 3000) and now I am working with (500, 1000).  This doesn't seem to change anything: the problem persists.

Any thoughts on what might be happening here?  

Many thanks!

**Comment by thedodd** [comment]
@joshgev haha nice. No worries at all. Let me know if there is anything I can help with `:)`.
