### ISSUE TITLE
Nodes never seem to enter NonVoter state

### ISSUE THREAD

**Issue by joshgev** [railgun-rs/actix-raft#58]
Hello,

I'm seeing an issue with the initialization of a new new Raft cluster using `actix-raft`. My application follows this procedure:

1. Start a `actix-web` server for node-to-node communication
2. Use Consul to register the node in Consul using an agent local to the instance of my software
3. Sleep for a while (for dev, since all nodes are local, I use 5 seconds)
4. Ask Consul for all available nodes that provide my service
5. Ask each node if a cluster already exists.
6. If a cluster *does* exists, do nothing (wait for the cluster to sense the new node and add it)
7. If a cluster *doesn't* exist, create one by sending an `InitWithConfig` message to the Raft actor. 

If my understanding of the docs is correct, this implementation represents fairly standard practice for a Raft cluster and an `actix-raft` cluster in particular.   However, when I run a test cluster, I get (from each node) an error explaining that calling `InitWithConfig` is not allowed because the node is in the `Follower` state with index 0. 

I understand why this is a problem, but I don't understand why a brand new node (totally blank initial state) is going (seemingly) directly into the follower state.  I suspect I am doing something wrong, but what is not clear.

I should say I have been able to hack around this issue by reporting an `InitialConfig` that contains the members of the cluster I am trying to form and by *not* sending the `InitWithConfig` message. Presumably this has the effect of tricking `actix-raft` into believing that there is already a cluster.  This "solution" seems to present other problems, though, when it comes to dynamically altering the cluster configuration.

Any insights here would be awesome.  As always, thanks in advance!

**Comment by thedodd** [comment]
Well, I've written a decent bit on how initial cluster formation is supposed to work here: https://railgun-rs.github.io/actix-raft/cluster-formation.html

If you are saying that the nodes are coming online in what should be a pristine state, but are not actually staying in a pristine state, then it sounds like there is some aspect of their initialization which is making them behave as though they are not pristine.

If you enable logging for `actix_raft`, do you see any information indicating what it is that is causing the nodes to transition to follower state?

---

Also, as an aside, I am in the process of moving this project off of Actix and squarely onto Tokio (with potential interop with async-std and other runtimes in the future). Lots of good stuff, and a few bug fixes already taken care of as part of this effort. The ability to use async/await directly in the code is a serious game changer for this project.

**Comment by joshgev** [comment]
Thanks for the reply, @thedodd .  I don't see any information coming out of the logs, except the warning (earlier I called it an error, but it is in fact a warning-level log line) about being in a follower state:

```
Raft received an InitWithConfig command, but the node is in state Follower with index 0
```.

What, generally, would cause a node to not be in a pristine state?  Clearly things like appending/applying log entries (including configuration changes) would change the state of a node, but nothing like that is happening when the node is coming online.

**Comment by joshgev** [comment]
@thedodd I think I found the answer to my question about initial membership config by reading through your code.  It seems that the initial `MembershipConfig` should look like this:

```
MembershipConfig {
  members: vec![this_node_id],
  non_voters: vec![],
  removing: vec![]
}
```

I tried that and `actix-raft` seems happy.  How does that look to you?

**Comment by thedodd** [comment]
@joshgev yes, that is definitely correct. That is why the `MembershipConfig` type does not derive default. It is expected that it will be initialized with some set of membership IDs. 

Some apps may want to build their Raft clusters with more "static" config, so I didn't want to make any assumptions about how folks wanted to structure that sort of stuff in their apps. However, at a minimum, the config should have the ID of itself in the config at startup.

**Comment by thedodd** [comment]
@joshgev sounds like this issue is clear to be closed now, correct?

**Comment by joshgev** [comment]
Ah, yes, I believe so. Closing now. Thanks again for your input!
