### ISSUE TITLE
Lagging replication streams will grow indefinitely

### ISSUE THREAD

**Issue by Diggsey** [railgun-rs/actix-raft#60]
I may be misreading, but it appears that lagging replication streams will accumulate new messages indefinitely. Items are added to the `buffered_outbound` field when in the `Lagging` state:
```rust
    fn handle(&mut self, msg: RSReplicate<D>, ctx: &mut Self::Context) -> Self::Result {
        // Always update line commit & index info first so that this value can be used in all AppendEntries RPCs.
        self.line_commit = msg.line_commit;
        self.line_index = msg.entry.index;

        // Get a mutable reference to an inner buffer if permitted by current state, else return.
        match &mut self.state {
            // NOTE: exceeding line rate buffer size is accounted for in the `handle_append_entries_response` handler.
            RSState::LineRate(inner) => inner.buffered_outbound.push(msg.entry),
            RSState::Lagging(inner) => inner.buffered_outbound.push(msg.entry), // <-- Here
            _ => return Ok(()),
        };

        self.drive_state(ctx);
        Ok(())
    }
```

But the buffered output field is only truncated when in the `LineRate` state:
```rust
            // If running at line rate, and our buffered outbound requests have accumulated too
            // much, we need to purge and transition to a lagging state. The target is not able to
            // replicate data fast enough.
            if let RSState::LineRate(inner) = &self.state {
                if inner.buffered_outbound.len() > (self.config.max_payload_entries as usize) {
                    return Box::new(self.transition_to_lagging(ctx)); // <-- Here
                }
            }
```

It's unclear why the `Lagging` state needs to store `buffered_outbound` messages at all, since it will fetch messages from the storage layer as needed.

(BTW, I've been writing my own Raft implementation on top of `act-zero` using this crate as a reference where the paper is unclear, and it's really quite enjoyable.)

**Comment by thedodd** [comment]
@Diggsey nice (re: your own Raft impl). So, that buffer does not accumulate data at all when in lagging state, as the raft core will not send it entries to replicate unless it is running at line-rate. I probably just neglected to remove that line.

However, logs of major updates coming in #59. All tokio based. I've recently re-worked the code, and the pattern is quite a bit more simple, and there are type level constrains in place now which disable something like that from happening on the type level.
