### ISSUE TITLE
Fallback conflict-resolution method uses the wrong term

### ISSUE THREAD

**Issue by Diggsey** [railgun-rs/actix-raft#61]
When the conflict optimization is not used (conflict_opt is None) the replication stream decrements its `match_index`. After doing so, it should also fetch the corresponding `match_term` from the storage layer.

Failing to do this will result in sending an incorrect `prev_log_term` in future `AppendEntries` requests, which will then be rejected, causing the replication to become stuck.

**Comment by thedodd** [comment]
@Diggsey as always, thanks for the report. The version of the code I have been writing over on #59 does account for this issue (by going directly to its log once it receives a conflict_opt report, and using the term of the entry found in the log).

I'll marked this issue for closure once #59 lands. That work?

**Comment by Diggsey** [comment]
Yep - I haven't been keeping up with #59 so I don't know what things have already been fixed there. Feel free to close as you see fit.
